version: '3'

services:
  db:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nest
      - MYSQL_USER=root
    ports:
      - 3306:3306
